## Imports

In [3]:
import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
pd.options.mode.chained_assignment = None

## Load Edges

In [22]:
edges = pd.read_csv('edges.csv')

trains = edges.query('type == "train"')
trains['duration'] = (trains['distance'] / trains['speed']) + trains['delay']
trains['price'] = trains['distance'] * trains['price_rate']
trains['worth'] = trains['duration'] / trains['price']

waters = edges.query('type == "water"')
waters['duration'] = (waters['distance'] / waters['speed']) + waters['delay']
waters['price'] = waters['distance'] * waters['price_rate']
waters['worth'] = waters['duration'] / waters['price']

airs = edges.query('type == "air"')
airs['duration'] = (airs['distance'] / airs['speed']) + airs['delay']
airs['price'] = airs['distance'] * airs['price_rate']
airs['worth'] = airs['duration'] / airs['price']

roads = edges.query('type == "road"')
roads['duration'] = (roads['distance'] / roads['speed']) + roads['delay']
roads['price'] = roads['distance'] * roads['price_rate']
roads['worth'] = roads['duration'] / roads['price']

computedEdges = pd.concat([trains, waters, airs, roads])
computedEdges = computedEdges.sort_values(by="worth", ascending=False)
computedEdges

,source,target,type,distance,speed,delay,price_rate,duration,price,worth
139,belo_horizonte,vitoria,train,664,50,1,0.09,14.280000,59.76,0.238956
140,macapa,belem,water,339,12,1,0.70,29.250000,237.30,0.123262
146,natal,fernando_de_noronha,water,374,12,1,0.70,32.166667,261.80,0.122867
28,joao_pessoa,recife,road,116,100,1,0.30,2.160000,34.80,0.062069
142,manaus,santarem,water,740,24,1,0.70,31.833333,518.00,0.061454
...,...,...,...,...,...,...,...,...,...,...
19,brasilia,fortaleza,air,1686,860,2,1.25,3.960465,2107.50,0.001879
10,brasilia,porto_velho,air,1904,860,2,1.25,4.213953,2380.00,0.001771
1,brasilia,manaus,air,1942,860,2,1.25,4.258140,2427.50,0.001754
23,brasilia,rio_branco,air,2249,860,2,1.25,4.615116,2811.25,0.001642
18,sao_paulo,fortaleza,air,2371,860,2,1.25,4.756977,2963.75,0.001605

## Save Data

In [24]:
computedEdges.to_csv('edges_computed.csv', index=False)